# Generated by Django 3.2.6 on 2021-08-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template_Tag',
            new_name='TemplateTag',
        ),
    ]
