# Generated by Django 3.2.6 on 2021-08-26 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates', '0002_remove_template_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='tags',
            field=models.ManyToManyField(blank=True, through='templates.Template_Tag', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='template',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
