# Generated by Django 3.2.6 on 2021-08-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_tag',
            name='created_at',
        ),
    ]
