# Generated by Django 3.2.6 on 2021-08-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_remove_template_tag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='templates.template'),
        ),
    ]
