# Generated by Django 3.2.6 on 2021-08-26 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates', '0007_template_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='likes',
            field=models.ManyToManyField(blank=True, through='templates.Template_Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template_like',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.template'),
        ),
    ]
