# Generated by Django 3.2.6 on 2021-08-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_auto_20210826_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_like',
            name='created_at',
        ),
    ]
