# Generated by Django 3.2.6 on 2021-08-26 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates', '0009_remove_template_like_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template_Like',
            new_name='Like',
        ),
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
